MyFirstDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from posts.views import main
from lovely.views import first, second, third
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name="main"),
    path('lovely/', include('lovely.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lovely/urls.py
from django.urls import path
from .views import first, second, third

app_name = "lovely"
urlpatterns = [
    path('first/', first, name="first"),
    path('second/', second, name="second"),
    path('third/', third, name="third"),
]

posts/urls.py
from django.urls import path
from .views import new, create, show, edit, update, delete

app_name = "posts"
urlpatterns = [
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('<int:post_id>/', show, name="show"),
    path('edit/<int:post_id>/', edit, name="edit"),
    path('update/<int:post_id>/', update, name="update"),
    path('delete/<int:post_id>/', delete, name="delete"),
]

lovely/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.urls import reverse

class Post(models.Model):
    class Meta:
        ordering = ['-created_at']
        
    POST_TYPES = [
        (0, "칼럼"),
        (1, "뉴스"),
        (2, "소설")
    ]
        
    title = models.CharField(max_length=200,
                            verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    view_count = models.IntegerField(default=0,
                                    verbose_name="조회수")
    _type = models.PositiveSmallIntegerField(choices=POST_TYPES,
                                            verbose_name="게시글타입")
    image = models.ImageField(upload_to="posts/img", default="posts/default/default_post_img.jpg")
    
    created_at = models.DateTimeField(auto_now_add=True,
                                     verbose_name="등록시간")
    updated_at = models.DateTimeField(auto_now=True,
                                     verbose_name="업데이트시간")
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('posts:show', args=[self.pk])

posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    _type = forms.ChoiceField(
        widget=forms.RadioSelect,
        label="게시글 종류",
        choices=Post.POST_TYPES,
        required=True
    )
    class Meta:
        model = Post
        fields = ['title', '_type', 'content', 'image']
        labels = {
            'title': '제목', 
            'content': '내용',
            'image': '게시글 사진'
        }
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control'
            })
        }

lovely/views.py
from django.shortcuts import render

def first(request):
    return render(request, 'lovely/first.html')


def second(request):
    return render(request, 'lovely/second.html')


def third(request):
    return render(request, 'lovely/third.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from .forms import PostForm
from django.views.decorators.http import require_POST
import pdb


def main(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'posts/main.html', context)


def new(request):
    context = {
        'form': PostForm()
    }
    return render(request, 'posts/new.html', context)


@require_POST
def create(request):
    form = PostForm(request.POST, request.FILES or None)
    if form.is_valid():
        form.save()
    return redirect(form.instance)
    
    
def show(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    default_view_count = post.view_count
    post.view_count = default_view_count + 1
    post.save()
    context = {
        'post': post
    }
    return render(request, 'posts/show.html', context)


def edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post,
        'form': PostForm(instance=post)
    }
    return render(request, 'posts/edit.html', context)


@require_POST
def update(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST, request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
    return redirect(post)
    

@require_POST
def delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('main')

        
        
        
        

MyFirstDjango/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/project.css' %}">

    <title>My First Django</title>
  </head>
  <body>
    {% include 'share/_navbar.html' %}
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

MyFirstDjango/templates/share/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'posts:new' %}">새글 쓰기</a>
      <a class="nav-item nav-link" href="#">Pricing</a>
      <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
    </div>
  </div>
</nav>

lovely/templates/lovely/first.html
{% extends 'base.html' %}

{% block content %}
{% include 'share/_navbar.html' %}
<h1>
    first
</h1>
{% endblock %}

lovely/templates/lovely/second.html
{% extends 'base.html' %}

{% block content %}
<h1>
    second
</h1>
{% endblock %}

lovely/templates/lovely/third.html
{% extends 'base.html' %}

{% block content %}
<h1>
    third
</h1>
{% endblock %}

posts/templates/posts/_form.html
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="{{ btn_value }}" class="btn btn-outline-primary">

posts/templates/posts/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>
        글 수정하기
    </h1>
    <form action="{% url 'posts:update' post.pk %}" method="POST" enctype="multipart/form-data">
        {% include 'posts/_form.html' with form=form btn_value="글수정" %}
    </form>
</div>
{% endblock %}

posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>
        성원's Blog
    </h1>
    <div class="row">
        {% for post in posts %}
        <div class="col-md-4 col-12">
            <div class="card" style="width: 18rem; margin-top: 20px;">
              {% if post.image %}
                  <img src="{{ post.image.url }}" class="card-img-top" alt="...">
              {% endif %}
              <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.content }}</p>
                <p>{{ post.created_at }}</p>
                <a href="{{ post.get_absolute_url }}" class="btn btn-primary">보러가기</a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>
        새로운 글 작성하기
    </h1>
    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
      {% include 'posts/_form.html' with form=form btn_value="글생성" %}
    </form>   
</div>
{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>
    게시글 상세 페이지 입니다.
    </h1>

    <h2>
        제목 : {{ post.title }}
    </h2>
    <h4>
        조회수 : {{ post.view_count }}
    </h4>

    <p>
        내용 : {{ post.content }}
    </p>
    <a href="{% url 'posts:edit' post.pk %}" class="btn btn-outline-primary">수정하기</a>
    <a href="#" class="btn btn-outline-danger" data-toggle="modal" data-target="#exampleModal">삭제하기</a>
    
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">정말 삭제하시겠습니까?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
            <form action="{% url 'posts:delete' post.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="삭제" class="btn btn-outline-danger">
            </form> 
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}